title: Abhigna Bheemineni
logo: /assets/myphoto.jpg
description: Actively applying for new roles | SoC Logic Design Engineer | 4+ years in Design Verification, Post Silicon Validation, Design For Testability | abhigna@pdx.edu | Living Here, Now
theme: jekyll-theme-minimal
