title: Abhigna Bheemineni
logo: /assets/img3.jpg
description: Actively Looking for a full time opportunity in IP/FPGA/SoC/CPU/GPU Design Verification, Post Silicon Validation, Design For Testability, Formal verification| Living Here, Now | abhigna@pdx.edu
theme: jekyll-theme-minimal
