title: Abhigna Bheemineni
logo: /assets/img3.jpg
description: SoC Logic Design Engineer with 4+ years of experience in Design Verification, Post Silicon Validation, Design For Testability | abhigna@pdx.edu | Living Here, Now | Interests- Photography, Hiking, Spirituality, Movies, Books.
theme: jekyll-theme-minimal
