title: Abhigna Bheemineni
logo: /assets/img3.jpg
description: Actively applying for new roles | SoC Logic Design Engineer | 4+ years in Design Verification, Post Silicon Validation, Design For Testability | abhigna@pdx.edu | Living Here, Now | Interests- Photography, Hiking, Movies.
theme: jekyll-theme-minimal
