title: Abhigna Bheemineni
logo: /assets/img3.jpg
description: Actively Looking for full time opportunities starting June 2024 in Design Verification, Post Silicon Validation, Design For Testability, Formal verification | Living Here, Now | abhigna@pdx.edu | [LinkedIn](https://www.linkedin.com/in/abhigna-bheemineni-6a055a132/)
theme: jekyll-theme-minimal
