title: Abhigna Bheemineni
logo: /assets/myphoto.jpg
description: |*| Actively applying for new roles |*| SoC Logic Design Engineer at Intel |*| 4+ years in Design Verification, Post Silicon Validation, Design For Testability |*| abhigna@pdx.edu |*|
theme: jekyll-theme-minimal
