title: Abhigna Bheemineni
logo: /assets/img3.jpg
description: Actively Looking for full time opportunities starting June 2024 in Design Verification, Post Silicon Validation, Design For Testability, Formal verification | Living Here, Now | abhigna@pdx.edu | Interests- Photography, Hiking, Spirituality, Movies, Books.
theme: jekyll-theme-minimal
