title: Abhigna Bheemineni
logo: /assets/img3.jpg
description: Actively Looking for full time opportunities starting June 2024 in Design Verification, Post Silicon Validation, Design For Testability, Formal verification | abhigna@pdx.edu | Living Here, Now | Interests- Photography, Hiking, Spirituality, Movies, Books.
theme: jekyll-theme-minimal
