title: Abhigna Bheemineni
logo: /assets/img1.jpg
description: Actively Looking for a full time opportunity in IP/FPGA/SoC/CPU/GPU Design Verification, Post Silicon Validation, Design For testability, Formal verification| Living Here, Now | abhigna@pdx.edu
#show_downloads: true
theme: jekyll-theme-minimal
